function [] = paper2plot_v1(ce, cn, cr, re, rn, rr, numNeurons, simTime)

hold on
subplot(2,3,1)
plotSpikeTrains(ce,numNeurons, simTime)
title('Exponential connections with simple cubic geometry', 'FontSize', 14, 'FontWeight', 'bold')
axis([0,simTime,0,numNeurons])
subplot(2,3,2)
plotSpikeTrains(cn,numNeurons, simTime)
title('Nearest neighbor connections with simple cubic geometry', 'FontSize', 14, 'FontWeight', 'bold')
axis([0,simTime,0,numNeurons])
subplot(2,3,3)
plotSpikeTrains(cr,numNeurons, simTime)
title('Random connections with simple cubic geometry', 'FontSize', 14, 'FontWeight', 'bold')
axis([0,simTime,0,numNeurons])
subplot(2,3,4)
plotSpikeTrains(re,numNeurons, simTime)
title('Exponential connections with random geometry', 'FontSize', 14,'FontWeight', 'bold')
axis([0,simTime,0,numNeurons])
subplot(2,3,5)
plotSpikeTrains(rn,numNeurons, simTime)
title('Nearest neighbor connections with random geometry', 'FontSize', 14, 'FontWeight', 'bold')
axis([0,simTime,0,numNeurons])
subplot(2,3,6)
plotSpikeTrains(rr,numNeurons, simTime)
title('Random connections with random geometry', 'FontSize', 14, 'FontWeight', 'bold')
axis([0,simTime,0,numNeurons])