function [] = paper2plot_v0(exp0, exp10, near0, near10, rand0, rand10, numNeurons, simTime)

hold on
subplot(4,3,1)
plotSpikeTrains(exp0,numNeurons)
title('Distance dependent connections with coupling strength 0 siemens')
axis([0,simTime,0,numNeurons])
subplot(4,3,2)
plotSpikeTrains(near0,numNeurons)
title('Nearest neighbor connections with coupling strength 0 siemens')
axis([0,simTime,0,numNeurons])
subplot(4,3,3)
plotSpikeTrains(rand0,numNeurons)
title('Random connections with coupling strength 0 siemens')
axis([0,simTime,0,numNeurons])
subplot(4,3,4)
powerSpectrumNeuralNetwork(exp0, simTime)
subplot(4,3,5)
powerSpectrumNeuralNetwork(near0, simTime)
subplot(4,3,6)
powerSpectrumNeuralNetwork(rand0, simTime)
subplot(4,3,7)
plotSpikeTrains(exp10,numNeurons)
title('Distance dependent connections with coupling strength 0.1 siemens')
axis([0,simTime,0,numNeurons])
subplot(4,3,8)
plotSpikeTrains(near10,numNeurons)
title('Nearest neighbor connections with coupling strength 0.1 siemens')
axis([0,simTime,0,numNeurons])
subplot(4,3,9)
plotSpikeTrains(rand10,numNeurons)
title('Random connections with coupling strength 0.1 siemens')
axis([0,simTime,0,numNeurons])
subplot(4,3,10)
powerSpectrumNeuralNetwork(exp10, simTime)
subplot(4,3,11)
powerSpectrumNeuralNetwork(near10, simTime)
subplot(4,3,12)
powerSpectrumNeuralNetwork(rand10, simTime)